<a href="https://colab.research.google.com/github/gh-ita/Warehouse-Robot/blob/main/WarehouseRobot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
gamma = 0.75
alpha = 0.9


# Building the env

In [ ]:
state = {
    'A':1,'B':2,'C':3,'D':4,'E':5,'F':6,'G':7,'H':8,'I':9,'J':10,'K':11,'L':12
}
action = [0,1,2,3,4,5,6,7,8,9,10,11]
reward = np.zeros([len(state),len(action)])

In [ ]:
reward[0,1] = 1
reward[1,0] = 1
reward[1,2] = 1
reward[1,5] = 1
reward[2,1] = 1
reward[2,6] = 1
reward[3,7] = 1
reward[4,8] = 1
reward[5,1] = 1
reward[5,9] = 1
reward[6,2] = 1
reward[6,6] = 1000
reward[6,7] = 1
reward[7,3] = 1
reward[7,6] = 1
reward[7,6] = 1
reward[7,11] = 1
reward[8,4] = 1
reward[8,9] = 1
reward[9,5] = 1
reward[9,8] = 1
reward[9,10] = 1
reward[10,9] = 1
reward[10,11] = 1
reward[11,7] = 1
reward[11,10] = 1

# Q-Learning

[[   0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   1.    0.    1.    0.    0.    1.    0.    0.    0.    0.    0.    0.]
 [   0.    1.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.]
 [   0.    1.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.]
 [   0.    0.    1.    0.    0.    0. 1000.    1.    0.    0.    0.    0.]
 [   0.    0.    0.    1.    0.    0.    1.    0.    0.    0.    0.    1.]
 [   0.    0.    0.    0.    1.    0.    0.    0.    0.    1.    0.    0.]
 [   0.    0.    0.    0.    0.    1.    0.    0.    1.    0.    1.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    1.]
 [   0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    1.    0.]]
