<a href="https://colab.research.google.com/github/gh-ita/Warehouse-Robot/blob/main/WarehouseRobot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
gamma = 0.75
alpha = 0.9
iterations = 1000


# Building the env

In [19]:
state = {
    'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6,'H':7,'I':8,'J':9,'K':10,'L':11
}
action = [0,1,2,3,4,5,6,7,8,9,10,11]
reward = np.zeros([len(state),len(action)])

In [4]:
reward[0,1] = 1
reward[1,0] = 1
reward[1,2] = 1
reward[1,5] = 1
reward[2,1] = 1
reward[2,6] = 1
reward[3,7] = 1
reward[4,8] = 1
reward[5,1] = 1
reward[5,9] = 1
reward[6,2] = 1
reward[6,6] = 1000
reward[6,7] = 1
reward[7,3] = 1
reward[7,6] = 1
reward[7,6] = 1
reward[7,11] = 1
reward[8,4] = 1
reward[8,9] = 1
reward[9,5] = 1
reward[9,8] = 1
reward[9,10] = 1
reward[10,9] = 1
reward[10,11] = 1
reward[11,7] = 1
reward[11,10] = 1

In [ ]:
print(reward)

[[   0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   1.    0.    1.    0.    0.    1.    0.    0.    0.    0.    0.    0.]
 [   0.    1.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    0.]
 [   0.    1.    0.    0.    0.    0.    0.    0.    0.    1.    0.    0.]
 [   0.    0.    1.    0.    0.    0. 1000.    1.    0.    0.    0.    0.]
 [   0.    0.    0.    1.    0.    0.    1.    0.    0.    0.    0.    1.]
 [   0.    0.    0.    0.    1.    0.    0.    0.    0.    1.    0.    0.]
 [   0.    0.    0.    0.    0.    1.    0.    0.    1.    0.    1.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.    1.    0.    1.]
 [   0.    0.    0.    0.    0.    0.    0.    1.    0.    0.    1.    0.]]


# Q-Learning

- Q learning is an algorithm that is used in finite environments, the states and actions are limited. It uses temporal difference and q values to find the optimal policy. Temporal difference serves as an estimator of how much the current q value of (state,action) needs to be updated to match the actual reward and future possible reward of the (state,action). The bellman equation is used to update each q value using the temporal difference and a learning rate.
In order to converge to the optimal policy we need to fix a certain number of iteration.
So Q learning is an algorithm that s uses both exploration and exploitation to find the optimal policy.

In [5]:
# Initialize the q values
qValues = np.zeros([len(state),len(action)])

In [6]:
for i in range(1000) :
  randState = np.random.randint(0, 11)
  pactions = []
  for index, value in enumerate(reward[randState, :]):
    if value != 0:
      pactions.append(index)
  #select a random action index
  randAction = np.random.choice(pactions)
  TD = reward[randState, randAction] + gamma*qValues[randAction, np.argmax(qValues[randAction,:])] - qValues[randState, randAction]
  qValues[randState, randAction] += alpha*TD
  qValues[randState, randAction] = round(qValues[randState, randAction], 0)

In [ ]:
qValues

array([[0.000e+00, 1.690e+03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.689e+03],
       [1.268e+03, 7.500e-01, 2.252e+03, 0.000e+00, 0.000e+00, 1.268e+03,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.689e+03],
       [0.000e+00, 1.690e+03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        3.001e+03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.689e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 2.252e+03, 0.000e+00, 0.000e+00, 0.000e+00, 1.689e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.268e+03, 0.000e+00, 0.000e+00, 1.689e+03],
       [0.000e+00, 1.690e+03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 1.268e+03, 0.000e+00, 1.689e+03],
       [0.000e+00, 7.500e-01, 2.252e+03, 0.000e+00, 0.000e+00, 0.000e+00,
        4.000e+03, 2.252e+03, 0.

# Inference

- The next step is to create a function which takes the any starting location as input and outputs the shortest path to our final destination.

In [9]:
index_to_location = { state: location for location, state in state.items()}
print(index_to_location)

{0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L'}


In [22]:
def route(start_loc,end_loc,state,index_to_location,qValues):
  start_state = state[start_loc]
  end_state = state[end_loc]
  short_route = []
  for state in range(len(qValues)):
     next_state = np.argmax(qValues[start_state],axis = 0)
     start_state = next_state
     short_route.append(index_to_location[next_state])
     if index_to_location[next_state] == end_loc :
      break
  print(short_route)
  return short_route

In [23]:
route('E','G',state,index_to_location,qValues)

['I', 'J', 'F', 'B', 'C', 'G']


['I', 'J', 'F', 'B', 'C', 'G']